on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
     - 'CICD/application/**'

steps:
- uses: actions/checkout@v2
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '6.0'
- run: dotnet build StudyGroup/CICD/application/Apps.sln

